name: Picking pearls
description: "Esempi di utilizzo di Pickup, il Manufacturing execution system (MES) di Esolver - Sistemi"
meta_description: "Blogging about Pickup MES"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /pickup
domain_name: 'https://mdm13.github.com/pickup'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]
scponline: 'http://www.scponline.it'
pickup: 'Pickup'

# Details for the RSS feed generator
url:            'https://mdm13.github.com'
author:         'SCP srl'
